#!/usr/bin/env bash
set -euo pipefail

# collect all posts from a specific day
archive_day() {
    # date format is 2025-11-28
    declare -a cmd
    local db_src
    local db_dst
    local prefix
    local query
    prefix=$1
    db_src=$2
    db_dst=$3
    db_dst_gz="${db_dst}.gz"

    # require args
    if [[ -z $prefix ]]; then
        printf "missing prefix argument\n"
        return 1;
    fi

    # do not squash existing zipped database
    if [[ -f "$db_dst_gz" ]]; then
        printf "output archive %s exists\n" "$db_dst_gz"
        return 1
    fi

    IFS= read -r -d '' query <<-SQL
ATTACH 'file:${db_src}?mode=ro' as js;
CREATE TABLE posts as SELECT * FROM js.posts WHERE json_extract(feedpost, '$.createdAt')
LIKE '${prefix}%';
DETACH js; 
VACUUM INTO '$db_dst';
SQL

    cmd+=(sqlite3)

    "${cmd[@]}" < <(printf "%s\n" "$query")
    gzip "$db_dst"
}

dashes_to_dots() {
    printf "%s" "$1" | sed 's/-/./g'
}

build_dest_filename() {
    local prefix
    prefix=$1

    prefix_nice="$(dashes_to_dots "$prefix")"
    printf "data/jetstream-%s.sqlite3" "$prefix_nice"
}

prefix_today() {
    TZ=UTC date -I
}

prefix_yesterday() {
    local current_ts
    current_ts=$(TZ=UTC date +%s)
    yesterday_ts=$(( current_ts - 86400 ))

    if date -d "@$yesterday_ts" '+%Y-%m-%d' >/dev/null 2>&1; then
        # Linux (GNU date)
        date_str=$(TZ=UTC date -d "@$yesterday_ts" '+%Y-%m-%d')
    else
        # BSD/macOS
        date_str=$(TZ=UTC date -r "$yesterday_ts" '+%Y-%m-%d')
    fi
    printf "%s" "$date_str"
}

printf "prefix_today(): %s\n" "$(prefix_today)"
printf "prefix_yesterday(): %s\n" "$(prefix_yesterday)"

archive_prefix="${1:-$(prefix_yesterday)}"
db_src="data/jetstream.sqlite3"
db_dst="$(build_dest_filename "$archive_prefix")"
printf "archiving all posts from yesterday %s ... " "$archive_prefix"
if archive_day "$archive_prefix" "$db_src" "$db_dst"; then
    printf "ok\n"
fi
