#!/usr/bin/env bash
set -euo pipefail

declare -a args
cfg_script_name="$(basename "$0")"
cfg_confirm=0 # false
cfg_force=0 # false

usage() {
    printf "Generate daily archive of jetstream in parquet format.\n\n"
    printf "%s [YYYY-MM-DD] [input.sqlite3]\n" "$cfg_script_name"
    printf "  --confirm  prompt to confirm action\n"
    printf "  --force    force overwrite of existing archive\n"
    printf "  --help\n"
    exit 1
}

# collect all posts from a specific day
archive_day() {
    # date format is 2025-11-28
    declare -a cmd
    local db_src
    local db_dst
    local prefix
    local query
    prefix=$1
    db_src=$2
    db_dst=$3

    # require args
    if [[ -z $prefix ]]; then
        printf "missing prefix argument\n"
        return 1;
    fi

    # do not squash existing zipped database
    if [[ -f "$db_dst" ]]; then
        printf "output archive %s exists\n" "$db_dst"
        return 1
    fi

    # restrict posts to the current day after parse
    read -r -d '' query <<-SQL || true
        attach '$db_src' as js (read_only);

        create table posts as (
            select * from js.posts
            where json_extract_string(feedpost, '$.createdAt')::TIMESTAMP >= '${prefix}'::TIMESTAMP
                and json_extract_string(feedpost, '$.createdAt')::TIMESTAMP < '${prefix}'::TIMESTAMP + interval '1 day'
        );

        detach js;

        -- write parquet file
        copy (select * from posts) to '$db_dst' (format parquet);
SQL

    cmd=(duckdb)

    "${cmd[@]}" < <(printf "%s\n" "$query")
}

dashes_to_dots() {
    printf "%s" "$1" | sed 's/-/./g'
}

build_dest_filename() {
    local prefix
    prefix=$1

    prefix_nice="$(dashes_to_dots "$prefix")"
    printf "data/archive/jetstream-%s.parquet" "$prefix_nice"
}

prefix_today() {
    TZ=UTC date -I
}

prefix_yesterday() {
    local current_ts
    current_ts=$(TZ=UTC date +%s)
    yesterday_ts=$(( current_ts - 86400 ))

    if date -d "@$yesterday_ts" '+%Y-%m-%d' >/dev/null 2>&1; then
        # Linux (GNU date)
        date_str=$(TZ=UTC date -d "@$yesterday_ts" '+%Y-%m-%d')
    else
        # BSD/macOS
        date_str=$(TZ=UTC date -r "$yesterday_ts" '+%Y-%m-%d')
    fi
    printf "%s" "$date_str"
}

# if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
#     usage
# fi

while (($# > 0)); do
    case $1 in
        "--help"|"-h")
            usage
            ;;
        "--confirm")
            cfg_confirm=1
            shift
            ;;
        "--force")
            cfg_force=1
            shift
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

# use yesterday's prefix
# printf "prefix_today(): %s\n" "$(prefix_today)"
# printf "prefix_yesterday(): %s\n" "$(prefix_yesterday)"
TZ=UTC date

archive_prefix=${args[0]:-"$(prefix_yesterday)"}
db_src=${args[1]:-"data/jetstream.sqlite3"}
db_dst="$(build_dest_filename "$archive_prefix")"
printf "using prefix: %s source: %s dest: %s\n" "$archive_prefix" "$db_src" "$db_dst"

if ((cfg_confirm)); then
    printf "confirm (y/n): "
    read -r answer
    if [[ $answer != "y" ]] && [[ $answer != "Y" ]]; then
        printf "exiting\n"
        exit 1
    fi
fi

if ((cfg_force)); then
    # remove file if present
    if [[ -f "$db_dst" ]]; then
        printf "removing existing archive %s ... " "$db_dst"
        if rm "$db_dst"; then
            printf "ok\n"
        fi
    fi
fi

printf "archiving all posts from %s ... " "$archive_prefix"
if archive_day "$archive_prefix" "$db_src" "$db_dst"; then
    printf "ok\n"
fi

TZ=UTC date
