#!/usr/bin/env bash

set -ueo pipefail

# global vars
declare -a args
declare -a cmd_time_series

output_dir="${HOME}/tmp"
script_name="$(basename "$0")"
# script_dir="$(cd "$(dirname "$0")" && pwd)" # does not work when invoked from symlink
script_dir="${HOME}/bluerift/bsky-api/scripts"
interval='1 minute' # must be minutes for step calculation
period='1 day'

usage() {
    printf "%s <term>\n" "$script_name"
    printf "  --interval <str>  specify bucket interval (minutes only) [%s]\n" "$interval"
    printf "  --output   <str>  specify graph output directory         [%s]\n" "$output_dir"
    printf "  --period   <str>  specify time period                    [%s]\n" "$period"
    exit 1
}

generate_output_name() {
    local output_dir=$1
    local term=$2
    local period=$3

    local output
    local period_string

    # require args
    if [[ -z $output_dir ]] || [[ -z $term ]] || [[ -z $period ]]; then
        printf "missing args\n" 1>&2
        return 1
    fi

    period_string=$(to_rrd_period "$period")
    output=$(printf "%s" "${output_dir}/${term}-${period_string}")
    output=$(printf "%s" "${output}" | sed 's/ /_/g') # replace spaces
    printf "%s" "$output"
}

remove_existing() {
    if [[ -f "$1" ]]; then
        rm "$1"
    fi
}

rrd_create() {
    local db
    local step
    local heartbeat
    local interval_minutes
    db=$1

    interval_minutes=$(printf "%s" "$interval" | sed 's/ .*$//')
    step=$((60 * interval_minutes))
    heartbeat=$((step * 2))

    remove_existing "$db"
    # subtract additional minute when calculating start time to compensate for data query time
    TZ=UTC rrdtool create "$db" \
    --start now-"${period_rrd}"-1m \
    --step $step \
    DS:count:GAUGE:"${heartbeat}":0:U \
    RRA:AVERAGE:0.5:1:44640 # max datapoints stored (31 days at 1 minute intervals)
}

rrd_graph() {
    declare -a cmd
    local date_str
    local db
    local output
    db=$1
    output=$2

    if [[ -z $db ]] || [[ -z $output ]]; then
        return 1
    fi

    date_str=$(TZ=UTC date | sed 's/:/\\:/g') # escape colons

    cmd+=(rrdtool graph "$output")
    cmd+=(--start now-"${period_rrd}")
    cmd+=(--end now)
    cmd+=(--title "BlueSky Term: $term")
    cmd+=(--vertical-label "posts / min")
    cmd+=(--width 1280)
    cmd+=(--height 300)
    cmd+=(--utc)
    cmd+=("DEF:count=${db}:count:AVERAGE")
    cmd+=("LINE1:count#0000FF:${term}")
    cmd+=("COMMENT:generated $date_str")

    TZ=UTC "${cmd[@]}"
}

rrd_update() {
    local db
    db=$1
    shift

    if [[ -z $db ]]; then
        return 1
    fi

    # rrdtool update "$rrd_output" "${ts}:${connections}"
    rrdtool update "$db" "$@"
}

# Converts a DuckDB INTERVAL type '3 hours' to rrdtool format '3h'
to_rrd_period() {
    local phrase
    phrase=$1

    local num
    local unit

    if [[ -z $phrase ]]; then
        return 1
    fi

    if [[ $phrase =~ ^[0-9]+\ +[a-zA-Z]+$ ]]; then
        num=$(printf "%s" "$phrase" | grep -Eo '^[0-9]+')
        unit=$(printf "%s" "$phrase" | grep -Eo '[a-zA-Z]+$')
        first_letter=${unit:0:1}
        # printf "num: '%s' unit: '%s'\n" "$num" "$unit"
        printf "%s%s\n" "$num" "$first_letter"
        return 0
    fi
    return 1
}

while (($# > 0)); do
    case $1 in
        --help|-h)
            usage
            ;;
        --interval)
            interval=$2
            shift 2
            ;;
        --output)
            output_dir=$2
            shift 2
            ;;
        --period)
            period=$2
            shift 2
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

term="${args[0]}"
period_rrd="$(to_rrd_period "$period")"

# require term name
if [[ -z $term ]]; then
    usage
fi

# assign filenames
rrd_output_db="$(generate_output_name "$output_dir" "$term" "$period").rrd"
rrd_output_image="$(generate_output_name "$output_dir" "$term" "$period").png"

# create database
rrd_create "$rrd_output_db" "$period"

# invoke `time_series` script in the same directory
cmd_time_series+=("$script_dir/time_series")
cmd_time_series+=(--interval "$interval")
cmd_time_series+=(--period "$period")
cmd_time_series+=(--rrd)
cmd_time_series+=("$term")

# populate database via data iteration
mapfile -t series_data < <("${cmd_time_series[@]}")

# update values and graph
rrd_update "$rrd_output_db" "${series_data[@]}"
rrd_graph "$rrd_output_db" "$rrd_output_image"

# remove output database
rm "$rrd_output_db"
