#!/usr/bin/env bash

# script_dir="$(cd "$(dirname "$0")" && pwd)"
ts="$(TZ=UTC date)"
output_dir="${HOME}/tmp/terms"
output_file="${output_dir}/index.html"
output_file_css="${output_dir}/style.css"

read -r -d '' html_prefix <<-HTML
<!DOCTYPE html>
<html>
    <head>
        <title>BlueSky Terms</title>
        <link rel="stylesheet" type="text/css" href="style.css"/>
    </head>
    <body>
        <h1>BlueSky Terms</h1>
        <div id="graphs">
HTML

read -r -d '' html_suffix <<-HTML
        </div>
        <div id="footer">
            <p>generated $ts</p>
        </div>
    </body>
</html>
HTML

# obtain file listing
mapfile -t image_files < <(ls "$output_dir"/*.png)

# write html
printf "%s\n" "$html_prefix" > "$output_file"

# generate all `<img>` tags
for image in "${image_files[@]}"; do
    image_basename="$(basename "$image")"
    read -r -d '' image_include <<-HTML
            <p class="graph"><img id="$image_basename" src="$image_basename"></p>
HTML

    printf "        %s\n" "$image_include" >> "$output_file"
done

printf "    %s\n" "$html_suffix" >> "$output_file"

# write css
read -r -d '' css_data <<-CSS
body {
    font-family: Monaco;
    background-color: #ffffff;
    text-align: center;
}

#graphs img {
    max-width: 90%;
}
CSS

printf "%s\n" "$(printf "%s\n" "$css_data")" > "$output_file_css"
