#!/usr/bin/env bash

set -eo pipefail

SCRIPT_NAME=$(basename "$0")

usage() {
    printf "%s <input.json> <output.duckdb>\n" "${SCRIPT_NAME}"
    exit 1
}

require_bin() {
    if which "${1}" >/dev/null; then
        return 0
    fi
    printf "missing binary: %s\n" "${1}"
    exit 1
}

require_file() {
    # one argument only
    if [[ $# != 1 ]]; then
        printf "%s: supply a single file argument\n" "${0}"
        exit 1
    fi
    
    # check file existence
    if [[ -f "${1}" ]]; then
        return 0
    fi
    printf "file not found: %s\n" "${1}"
    exit 1
}

require_no_file() {
    if [[ -f "${1}" ]]; then
        printf "file already exists: %s\n" "${1}"
        exit 1
    fi
    return 0
}

export_json_file() {
    local db
    local file_json
    declare -a cmd
    local time_start
    local time_stop

    db=$1
    file_json=$2
    time_start="$(TZ=UTC date -I)T00:00:00"
    time_stop="$(TZ=UTC date -I)T23:59:59"

    cmd+=(sqlite3 -readonly)
    cmd+=("$db")
    cmd+=("select feedpost from posts where json_extract(feedpost, '$.feedpost.createdAt') >= '$time_start' and json_extract(feedpost, '$.feedpost.createdAt') <= '$time_stop' order by rowid")

    "${cmd[@]}" > "$file_json"
}

import_json() {
    local file_json
    local file_duck
    local file_duck_tmp
    local partial_lines
    local cmd
    declare -a args

    # parse options
    while [[ $# -gt 0 ]]; do
        case $1 in
            "--partial")
                shift
                partial_lines=$1
                shift
                ;;
            *)
                args+=("$1")
                shift
                ;;
        esac
    done

    file_json="${args[0]}"
    file_duck="${args[1]}"
    file_duck_tmp="${file_duck}.tmp"
    # require_no_file "${file_duck}"
    require_no_file "${file_duck_tmp}"

    # partail import
    if (( partial_lines > 0 )); then
        file_json_partial="${file_json}.partial"

        printf "reading last %s lines from %s ... " "${partial_lines}" "${file_json}"
        if tail -n "${partial_lines}" "${file_json}" > "${file_json_partial}"; then
            # use partial file
            file_json="${file_json_partial}"
        fi
    fi
    # sample entire file before processing to avoid any unexpected fields
    cmd=$(printf "create table posts as select * from read_json_auto('%s', sample_size = -1)" "${file_json}")
    # printf "cmd: %s\n" "${cmd}"
    # duckdb "${file_duck}" "${cmd}"
    nice duckdb "${file_duck_tmp}" "${cmd}" &>/dev/null
    # replace old file
    mv "${file_duck_tmp}" "${file_duck}"
}

file_info() {
    for f in "$@"; do
        printf "%s %s bytes\n" "${f}" "$(stat -c "%s" "${f}")"
    done
}

fts_index() {
    local file_duck
    local cmd
    file_duck=$1

    cmd=$(printf "pragma create_fts_index(posts, cid, text, stemmer = 'porter', stopwords = 'english', ignore = '(\\.|[^a-z])+', strip_accents = 1, lower = 1, overwrite = 0)")
    duckdb "${file_duck}" "${cmd}" &>/dev/null
}

# check for help args
for arg in "$@"; do
    if [[ "${arg}" == "--help" ]] || [[ "${arg}" == "-h" ]]; then
        usage
    fi
done

declare -a args
partial_lines=0

while [[ $# -gt 0 ]]; do
    case $1 in
        "--partial")
            shift
            partial_lines=$1
            shift
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

require_bin duckdb

sqlite_source="data/jetstream.sqlite3"
json_source=${args[0]:-"data/jetstream.json"}
duckdb_dest=${args[1]:-"data/jetstream.duckdb"}

printf "%s starting build\n" "$(TZ=UTC date)"

# remove database before rebuild if present
# if [[ -f "${duckdb_dest}" ]]; then
#     rm "${duckdb_dest}"
# fi

printf "export json to file ... "
if ! export_json_file "${sqlite_source}" "${json_source}"; then
    printf "error\n"
    exit 1
fi
printf "ok\n"

require_file "${json_source}"

printf "importing %s to %s ... " "${json_source}" "${duckdb_dest}"
if ! import_json --partial "${partial_lines}" "${json_source}" "${duckdb_dest}"; then
    printf "error\n"
    exit 1
fi
printf "ok\n"

printf "implementing fts ... "
if ! fts_index "${duckdb_dest}"; then
    printf "error\n"
    exit 1
fi
printf "ok\n"

printf "removing temp file %s ... " "${json_source}"
if ! rm "${json_source}"; then
    printf "error\n"
    exit 1
fi
printf "ok\n"

printf "%s build complete\n" "$(TZ=UTC date)"
# file_info "${json_source}" "${duckdb_dest}"
