#!/usr/bin/env bash

set -uo pipefail

create_sqlite_clone() {
    declare -a cmd
    local db
    local db_clone
    local db_clone_tmp

    db="data/jetstream.sqlite3"
    db_clone="data/sync.sqlite3"
    db_clone_tmp="data/sync_new.sqlite3"
    # clone new database
    read -r -d '' q <<-SQL || true
        .clone '$db_clone_tmp'
SQL

    # remove db_clone_tmp if present from previous failure
    rm "$db_clone_tmp" &>/dev/null

    # sqlite3 -readonly data/jetstream.sqlite3 ".clone 'data/sync_new.sqlite3'"
    cmd+=(sqlite3 -readonly)
    cmd+=("$db")
    if ! "${cmd[@]}" < <(printf "%s" "$q"); then
        printf "error cloning database\n"
        return 1
    fi

    # remove database and wal files
    if [[ -f "${db_clone}" ]]; then rm "${db_clone}" &>/dev/null; fi
    if [[ -f "${db_clone}-wal" ]]; then rm "${db_clone}-wal" &>/dev/null; fi
    if [[ -f "${db_clone}-shm" ]]; then rm "${db_clone}-shm" &>/dev/null; fi

    # replace with new
    mv "$db_clone_tmp" "$db_clone"
    # enable WAL for sqlite3-rsync
    sqlite3 "$db_clone" "pragma journal_mode=wal"
}

create_sqlite_clone
