#!/usr/bin/env bash

declare -a args
declare -a cmd

cfg_script_name="$(basename "$0")"

usage() {
    printf "usage: %s <db1.parquet> <db2.parquet>\n" "$cfg_script_name"
    exit 1
}

# parse options
while (($# > 0)); do
    case $1 in
        --help)
            shift
            usage
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

# require two arguments
if ((${#args[@]} < 2)); then
    usage
fi

db1="${args[0]}"
db2="${args[1]}"

read -r -d '' query <<-SQL
    -- Compare Parquet files to compare the number of posts captured
    -- between the go jetstream client and this one.
    
    -- create basic raw parquet views
    create view posts_js1 as
        select * from '$db1';
    
    create view posts_js2 as
        select * from '$db2';
    
    -- parse datetime field for logical comparisons
    create view js1_parsed as
        select json_extract_string(feedpost, '$.createdAt')::TIMESTAMPTZ created_at,
            *
        from posts_js1;
    
    create view js2_parsed as
        select json_extract_string(feedpost, '$.createdAt')::TIMESTAMPTZ created_at,
            *
        from posts_js2;
    
    -- obtain counts
    select 'db1' as label, '$db1' as source, count(*) as posts from js1_parsed
    
    union all
    select 'db2', '$db2', count(*) as posts from js2_parsed;
    
    -- compare by hour
    create temporary table js1 as
        select substr(created_at::VARCHAR, 0, 14) as ts, count(*) as count
        from js1_parsed group by ts
        order by ts;
    
    create temporary table js2 as
        select substr(created_at::VARCHAR, 0, 14) as ts, count(*) as count
        from js2_parsed group by ts
        order by ts;
    
    create temporary table comparison as
        select js1.ts as hour, js1.count as db1, js2.count as db2, abs(js1.count - js2.count) as disparity from js1 left join js2 on js1.ts = js2.ts;
    
    select * from comparison;
    
    select 'cumulative disparity' as key, abs(sum(disparity)) as value from comparison;
SQL

cmd=(duckdb)

"${cmd[@]}" < <(printf "%s\n" "$query")
