#!/usr/bin/env bash

set -eo pipefail

# variables
declare -a args
script_name=$(basename "$0")
cfg_dry_run=0 # false

usage() {
    printf "%s [date_prefix]\n" "$script_name"
    exit 1
}

prefix_today() {
    TZ=UTC date -I
}

while (($# > 0)); do
    case $1 in
        --help|-h)
            usage
            ;;
        --dry-run)
            cfg_dry_run=1 # true
            shift
            ;;
        *)
            args+=("$1")
            shift
            ;;
    esac
done

current_db="data/jetstream.sqlite3"
new_db="data/new.sqlite3"
date_prefix=${args[0]:-$(prefix_today)}

read -r -d '' query<<-SQL || true
    ATTACH 'file:${current_db}?mode=ro' as js;
    CREATE TABLE posts AS SELECT * FROM js.posts
    WHERE json_extract(feedpost, '$.createdAt') >= '$date_prefix';
    DETACH js;
SQL

printf "date_prefix: %s\n" "$date_prefix"
printf "query: %s\n" "$query"

if ((cfg_dry_run)); then
    exit 0
fi

printf "creating new database ... "
if sqlite3 "$new_db" < <(printf "%s\n" "$query"); then
    printf "ok\n"
fi
